apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: first-api
build:
  local:
    push: false
  artifacts:
    - image: lucasmagalhaes88/first-api
      context: src
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yml
    - k8s/service.yml
