apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-santodigital
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: lucasmagalhaes88/first-api:5dcbeee
        ports:
        - containerPort: 8000
